name=MLPico
version=1.0.0
author=George Chousos
maintainer=gxousos@gmail.com
sentence=Multilayer Perceptron (MLP) Library.
paragraph=Static-allocation MLP inference in ANSI C using 2-slot circular buffer with fixed stride indexing. An easy to use, minimal MLP alternative to GiorgosXou/NeuralNetworks enhanced with PROGMEM, int-quantization etc.
category=Data Processing
url=https://github.com/GiorgosXou/MLPico
architectures=*
includes=mlpico.h
